name: Machine Learning Workflow

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  train_and_evaluate:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run pre-processing script
      run: python preprocessing.py

    - name: Run training and evaluation script
      run: python training_eval.py

  deploy_to_heroku:
    needs: train_and_evaluate
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Deploy to Heroku
      if: ${{ success() }}
      run: |
        git remote add heroku ${{ secrets.HEROKU_REMOTE_URL }}
        git push heroku mains