name: Machine Learning Workflow

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  train_and_evaluate:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Parse dataset from firebase
      run: python firebase.py

    - name: Run pre-processing script
      run: python preprocessing.py

    - name: Run training and evaluation script
      run: python training_eval.py

    - name: Run Flask application locally
      run: |
        export FLASK_APP=app.py
        flask run


#deploy_to_heroku:
#    needs: train_and_evaluate
#    runs-on: ubuntu-latest
#    steps:
#    - name: Check out repository
#      uses: actions/checkout@v2

#    - name: Deploy to Heroku
#      if: ${{ success() }}
#      uses: akhileshns/heroku-deploy@v3.8.8
#      with:
#        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
#        heroku_email: szkhan.bee19@gmail.com
#        usedocker: true"""